name: Deploy Maven Site to GitHub Pages

on:
  push:
    branches:
      - main # Executa sempre que houver push na branch principal

permissions:
  contents: write # Permissão necessária para criar a branch de páginas

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Gerar Site com o Maven
        run: mvn clean site

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/ # Pasta onde o Maven gera o site estático
