name: Deploy Maven Site to GitHub Pages

on:
  push:
    branches:
      - main # Ajuste para 'master' se o seu repositório usar esse nome

permissions:
  contents: read
  pages: write
  id-token: write

# Procure por esta seção no seu arquivo:
concurrency:
  group: "pages-v2" # Mudamos de "pages" para "pages-v2"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configurar ambiente do GitHub Pages
        uses: actions/configure-pages@v5

      - name: Gerar Site com o Maven
        run: mvn clean site

      - name: Compactar os arquivos gerados
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/site'

      - name: Publicar no GitHub Pages Oficial
        id: deployment
        uses: actions/deploy-pages@v4
